blank_issues_enabled: false
contact_links:
  - name: Hubspot Developer Forum
    url: https://community.hubspot.com/t5/HubSpot-Developers/ct-p/developers
    about: Join developer forums to ask questions and interact with community.
